{{- if .Values.webhooks.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "infernex-bridge.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: webhook-server
  selector:
    app.kubernetes.io/name: {{ include "infernex-bridge.name" . }}
{{- end }}
