//go:build !ignore_autogenerated

/*
 * Copyright (c) 2026 Huawei Technologies Co., Ltd.
 * openFuyao is licensed under Mulan PSL v2.
 * You can use this software according to the terms and conditions of the Mulan PSL v2.
 * You may obtain a copy of Mulan PSL v2 at:
 *          http://license.coscl.org.cn/MulanPSL2
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
 * EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
 * MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
 * See the Mulan PSL v2 for more details.
 */

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/api/core/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	apiv1 "sigs.k8s.io/gateway-api-inference-extension/api/v1"
	apisv1 "sigs.k8s.io/gateway-api/apis/v1"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CacheIndexerComponentSpec) DeepCopyInto(out *CacheIndexerComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CacheIndexerComponentSpec.
func (in *CacheIndexerComponentSpec) DeepCopy() *CacheIndexerComponentSpec {
	if in == nil {
		return nil
	}
	out := new(CacheIndexerComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentSpec) DeepCopyInto(out *ComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentSpec.
func (in *ComponentSpec) DeepCopy() *ComponentSpec {
	if in == nil {
		return nil
	}
	out := new(ComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComponentStatus) DeepCopyInto(out *ComponentStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComponentStatus.
func (in *ComponentStatus) DeepCopy() *ComponentStatus {
	if in == nil {
		return nil
	}
	out := new(ComponentStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EagleEyeComponentSpec) DeepCopyInto(out *EagleEyeComponentSpec) {
	*out = *in
	if in.HardwareMonitor != nil {
		in, out := &in.HardwareMonitor, &out.HardwareMonitor
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HardwareDiagnosis != nil {
		in, out := &in.HardwareDiagnosis, &out.HardwareDiagnosis
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.NetworkPerformanceExporter != nil {
		in, out := &in.NetworkPerformanceExporter, &out.NetworkPerformanceExporter
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EagleEyeComponentSpec.
func (in *EagleEyeComponentSpec) DeepCopy() *EagleEyeComponentSpec {
	if in == nil {
		return nil
	}
	out := new(EagleEyeComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EnabledComponentSpec) DeepCopyInto(out *EnabledComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EnabledComponentSpec.
func (in *EnabledComponentSpec) DeepCopy() *EnabledComponentSpec {
	if in == nil {
		return nil
	}
	out := new(EnabledComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GatewayRefSpec) DeepCopyInto(out *GatewayRefSpec) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(NamedRef)
		**out = **in
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(apisv1.GatewaySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GatewayRefSpec.
func (in *GatewayRefSpec) DeepCopy() *GatewayRefSpec {
	if in == nil {
		return nil
	}
	out := new(GatewayRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HTTPRouteRefSpec) DeepCopyInto(out *HTTPRouteRefSpec) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(NamedRef)
		**out = **in
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(apisv1.HTTPRouteSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HTTPRouteRefSpec.
func (in *HTTPRouteRefSpec) DeepCopy() *HTTPRouteRefSpec {
	if in == nil {
		return nil
	}
	out := new(HTTPRouteRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexComponentStatuses) DeepCopyInto(out *InferNexComponentStatuses) {
	*out = *in
	if in.InferenceEngine != nil {
		in, out := &in.InferenceEngine, &out.InferenceEngine
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.HermesRouter != nil {
		in, out := &in.HermesRouter, &out.HermesRouter
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.ProxyServer != nil {
		in, out := &in.ProxyServer, &out.ProxyServer
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.CacheIndexer != nil {
		in, out := &in.CacheIndexer, &out.CacheIndexer
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.Mooncake != nil {
		in, out := &in.Mooncake, &out.Mooncake
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.PDOrchestrator != nil {
		in, out := &in.PDOrchestrator, &out.PDOrchestrator
		*out = new(ComponentStatus)
		**out = **in
	}
	if in.EagleEye != nil {
		in, out := &in.EagleEye, &out.EagleEye
		*out = new(ComponentStatus)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexComponentStatuses.
func (in *InferNexComponentStatuses) DeepCopy() *InferNexComponentStatuses {
	if in == nil {
		return nil
	}
	out := new(InferNexComponentStatuses)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexService) DeepCopyInto(out *InferNexService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexService.
func (in *InferNexService) DeepCopy() *InferNexService {
	if in == nil {
		return nil
	}
	out := new(InferNexService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferNexService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceConfig) DeepCopyInto(out *InferNexServiceConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceConfig.
func (in *InferNexServiceConfig) DeepCopy() *InferNexServiceConfig {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferNexServiceConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceConfigList) DeepCopyInto(out *InferNexServiceConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferNexServiceConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceConfigList.
func (in *InferNexServiceConfigList) DeepCopy() *InferNexServiceConfigList {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferNexServiceConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceConfigSpec) DeepCopyInto(out *InferNexServiceConfigSpec) {
	*out = *in
	in.InferNexServiceSpec.DeepCopyInto(&out.InferNexServiceSpec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceConfigSpec.
func (in *InferNexServiceConfigSpec) DeepCopy() *InferNexServiceConfigSpec {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceList) DeepCopyInto(out *InferNexServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InferNexService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceList.
func (in *InferNexServiceList) DeepCopy() *InferNexServiceList {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferNexServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceSpec) DeepCopyInto(out *InferNexServiceSpec) {
	*out = *in
	if in.SourceRef != nil {
		in, out := &in.SourceRef, &out.SourceRef
		*out = new(SourceRef)
		**out = **in
	}
	if in.BaseRefs != nil {
		in, out := &in.BaseRefs, &out.BaseRefs
		*out = make([]NamedRef, len(*in))
		copy(*out, *in)
	}
	if in.Model != nil {
		in, out := &in.Model, &out.Model
		*out = new(LLMModelSpec)
		**out = **in
	}
	if in.Engine != nil {
		in, out := &in.Engine, &out.Engine
		*out = new(InferenceEngineSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.IntelligentGatewayRouting != nil {
		in, out := &in.IntelligentGatewayRouting, &out.IntelligentGatewayRouting
		*out = new(IntelligentGatewayRoutingSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(InfernexComponentsSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceSpec.
func (in *InferNexServiceSpec) DeepCopy() *InferNexServiceSpec {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferNexServiceStatus) DeepCopyInto(out *InferNexServiceStatus) {
	*out = *in
	if in.Components != nil {
		in, out := &in.Components, &out.Components
		*out = new(InferNexComponentStatuses)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferNexServiceStatus.
func (in *InferNexServiceStatus) DeepCopy() *InferNexServiceStatus {
	if in == nil {
		return nil
	}
	out := new(InferNexServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceEngineSpec) DeepCopyInto(out *InferenceEngineSpec) {
	*out = *in
	in.InferenceEngineWorkloadSpec.DeepCopyInto(&out.InferenceEngineWorkloadSpec)
	if in.Prefill != nil {
		in, out := &in.Prefill, &out.Prefill
		*out = new(InferenceEngineWorkloadSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceEngineSpec.
func (in *InferenceEngineSpec) DeepCopy() *InferenceEngineSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceEngineSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceEngineWorkloadSpec) DeepCopyInto(out *InferenceEngineWorkloadSpec) {
	*out = *in
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Worker != nil {
		in, out := &in.Worker, &out.Worker
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.DataParallelSize != nil {
		in, out := &in.DataParallelSize, &out.DataParallelSize
		*out = new(int32)
		**out = **in
	}
	if in.DataParallelSizeLocal != nil {
		in, out := &in.DataParallelSizeLocal, &out.DataParallelSizeLocal
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceEngineWorkloadSpec.
func (in *InferenceEngineWorkloadSpec) DeepCopy() *InferenceEngineWorkloadSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceEngineWorkloadSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferencePoolRefSpec) DeepCopyInto(out *InferencePoolRefSpec) {
	*out = *in
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(NamedRef)
		**out = **in
	}
	if in.Spec != nil {
		in, out := &in.Spec, &out.Spec
		*out = new(apiv1.InferencePoolSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferencePoolRefSpec.
func (in *InferencePoolRefSpec) DeepCopy() *InferencePoolRefSpec {
	if in == nil {
		return nil
	}
	out := new(InferencePoolRefSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfernexComponentsSpec) DeepCopyInto(out *InfernexComponentsSpec) {
	*out = *in
	if in.CacheIndexer != nil {
		in, out := &in.CacheIndexer, &out.CacheIndexer
		*out = new(CacheIndexerComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Mooncake != nil {
		in, out := &in.Mooncake, &out.Mooncake
		*out = new(MooncakeComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.PDOrchestrator != nil {
		in, out := &in.PDOrchestrator, &out.PDOrchestrator
		*out = new(PDOrchestratorComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.EagleEye != nil {
		in, out := &in.EagleEye, &out.EagleEye
		*out = new(EagleEyeComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfernexComponentsSpec.
func (in *InfernexComponentsSpec) DeepCopy() *InfernexComponentsSpec {
	if in == nil {
		return nil
	}
	out := new(InfernexComponentsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IntelligentGatewayRoutingSpec) DeepCopyInto(out *IntelligentGatewayRoutingSpec) {
	*out = *in
	if in.Router != nil {
		in, out := &in.Router, &out.Router
		*out = new(ComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.HTTPRoute != nil {
		in, out := &in.HTTPRoute, &out.HTTPRoute
		*out = new(HTTPRouteRefSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(GatewayRefSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.InferencePool != nil {
		in, out := &in.InferencePool, &out.InferencePool
		*out = new(InferencePoolRefSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IntelligentGatewayRoutingSpec.
func (in *IntelligentGatewayRoutingSpec) DeepCopy() *IntelligentGatewayRoutingSpec {
	if in == nil {
		return nil
	}
	out := new(IntelligentGatewayRoutingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LLMModelSpec) DeepCopyInto(out *LLMModelSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LLMModelSpec.
func (in *LLMModelSpec) DeepCopy() *LLMModelSpec {
	if in == nil {
		return nil
	}
	out := new(LLMModelSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MooncakeComponentSpec) DeepCopyInto(out *MooncakeComponentSpec) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Master != nil {
		in, out := &in.Master, &out.Master
		*out = new(TemplateComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MooncakeComponentSpec.
func (in *MooncakeComponentSpec) DeepCopy() *MooncakeComponentSpec {
	if in == nil {
		return nil
	}
	out := new(MooncakeComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NamedRef) DeepCopyInto(out *NamedRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NamedRef.
func (in *NamedRef) DeepCopy() *NamedRef {
	if in == nil {
		return nil
	}
	out := new(NamedRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PDOrchestratorComponentSpec) DeepCopyInto(out *PDOrchestratorComponentSpec) {
	*out = *in
	if in.ElasticScaler != nil {
		in, out := &in.ElasticScaler, &out.ElasticScaler
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Tidal != nil {
		in, out := &in.Tidal, &out.Tidal
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.ResourceScalingGroup != nil {
		in, out := &in.ResourceScalingGroup, &out.ResourceScalingGroup
		*out = new(EnabledComponentSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PDOrchestratorComponentSpec.
func (in *PDOrchestratorComponentSpec) DeepCopy() *PDOrchestratorComponentSpec {
	if in == nil {
		return nil
	}
	out := new(PDOrchestratorComponentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SourceRef) DeepCopyInto(out *SourceRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SourceRef.
func (in *SourceRef) DeepCopy() *SourceRef {
	if in == nil {
		return nil
	}
	out := new(SourceRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TemplateComponentSpec) DeepCopyInto(out *TemplateComponentSpec) {
	*out = *in
	if in.Template != nil {
		in, out := &in.Template, &out.Template
		*out = new(v1.PodTemplateSpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TemplateComponentSpec.
func (in *TemplateComponentSpec) DeepCopy() *TemplateComponentSpec {
	if in == nil {
		return nil
	}
	out := new(TemplateComponentSpec)
	in.DeepCopyInto(out)
	return out
}
